name: 'check ranking for all keywords'

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our api route
        run: |
          curl 'https://6d9sir-ip-182-66-218-121.tunnelmole.net/api/check-for-all-keywords'